[package]
name = "core_prac0"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
crossbeam = "0.8.4"
tokio = {version = "1.40.0", features = ["full"]}
num_cpus = "1.16.0"
libc = "0.2.161"
rand = {version="0.8.5"}
rusqlite = "0.32.1"
